version: '3.8'

services:

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-server
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - EUREKA_SERVER_ADDRESS=http://discovery-server:8761/eureka
    networks:
      - microservice-network
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-product:
    build: ./ms-product
    container_name: ms-product
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ms-product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pasha
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - microservice-network
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy

  ms-payment:
    build: ./ms-payment
    container_name: ms-payment
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ms-product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pasha
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - microservice-network
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy

  ms-order:
    build: ./ms-order
    container_name: ms-order
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ms-product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pasha
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - microservice-network
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy

  ms-auth:
    build: ./msauthartifact
    container_name: ms-auth
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ms-product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pasha
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - microservice-network
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    networks:
      - microservice-network
    depends_on:
      config-server:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ms-product
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pasha
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservice-network
    depends_on:
      - ms-order
      - ms-product
      - ms-payment
      - ms-auth
      - api-gateway
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - microservice-network
    depends_on:
      - prometheus
networks:
  microservice-network:
    driver: bridge

volumes:
  postgres-data:
  grafana-data: