server:
  port: 9090

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
springdoc:
  swagger-ui:
    urls:
      - name: ms-order
        url: /orders/v3/api-docs
      - name: ms-product
        url: /products/v3/api-docs
      - name: ms-payment
        url: /payments/v3/api-docs
jwt:
  secret: YjEyNGYwNTRkZDA2NDJlYWIwYTM2YzkwMmE1ZmQxNDY=
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}